
/*
 { "problemId": number   /* The `id` of the game configuration */
  , "seed":      number   /* The seed for the particular game */
  , "tag":       string   /* A tag for this solution. */
  , "solution":  Commands
  }
  tag is auto-generated by server if not given
 */
case class Solution(problemId: Int, seed: Int, solution: String)

object SolutionCompanion {

  def apply(problemId: Int, seed: Int, commands: Seq[Move]): Solution = {
    Solution(problemId, seed, commands.toIterator.map(_.toChar).mkString)
  }
}
