
/*
 { "problemId": number   /* The `id` of the game configuration */
  , "seed":      number   /* The seed for the particular game */
  , "tag":       string   /* A tag for this solution. */
  , "solution":  Commands
  }
  tag is auto-generated by server if not given
 */
case class Solution(problemId: Int, seed: Int, solution: String)

object SolutionCompanion {

  def apply(problemId: Int, seed: Int, commands: Seq[Seq[Move]]): Solution = {
    // one line per unit
    val s = commands.toIterator.map(cs => cs.toIterator.map(_.toChar).mkString).mkString("\n")
    Solution(problemId, seed, s)
  }
}
